BookLibrary2/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using BookLibrary2.Models;

namespace BookLibrary2.Controllers
{
   
    public class AuthorController : Controller
    {

        [HttpGet]
        public async Task<ActionResult> Index(int pageNumber = 1, string searchString = null)
        {

            await CheckSetRights();
            DataTable table;
            do
            {
                table = await new Author().GetByPageAsync(pageNumber, searchString);
                if (table.Rows.Count == 0 && pageNumber > 1)
                {
                    pageNumber -= 1;
                    table = await (new Author()).GetByPageAsync(pageNumber, searchString);
                }

            } while (pageNumber > 1 && table.Rows.Count == 0);

            if (!string.IsNullOrEmpty(searchString))
            {
                ViewData["searchString"] = searchString;
            }
            else
            {
                ViewData["searchString"] = null;
            }

            ViewData["pageNumber"] = pageNumber;
            ViewData["pageSize"] = Book.PageSize;
            return View(table);           
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                result = View(new Author());
            }
            return result;
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(Author author)
        {
            ActionResult result;
            if (ModelState.IsValid)
            {
                await author.CreateAsync();
                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Create");
            }
            return result;
          
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Edit(int idAuthor)
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                Author author = await (new Author()).GetByIdAsync(idAuthor);
                if (author != null)
                {
                    result = View(author);
                }
                else
                {
                    result = RedirectToAction("Index");
                }
            }
            return result;                   
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Edit(Author author)
        {
            ActionResult result;
            if (ModelState.IsValid)
            {
                await author.UpdateAsync();
                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Edit", new RouteValueDictionary { { "idAuthor", author.IdAuthor } });
            }
            return result;       
        }

        private async Task<ActionResult> GetUserRout()
        {
            ActionResult result = null;
            if (!(await AdminLogin.CheckLoginAdminAccess(User.Identity.Name)))
            {
                result = RedirectToAction("Index", "Book");
            }
            return result;
        }  
    
        private async Task CheckSetRights()
        {
            if (User.Identity.IsAuthenticated)
            {
                string login = User.Identity.Name;
                bool isAdmin = await AdminLogin.CheckLoginAdminAccess(login);
                if (isAdmin)
                {
                    ViewData["isAdmin"] = true;
                }
                else
                {
                    User us = await new User().GetByEmailAsync(login);
                    ViewData["idUser"] = us.IdUser;
                }
            }
        }
    }
}

BookLibrary2/Controllers/BookAuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System.Web.Routing;
using BookLibrary2.Models;

namespace BookLibrary2.Controllers
{
    
    public class BookAuthorController : Controller
    {
       [HttpGet]
        public async Task<ActionResult> Index(long  idBook)
       {
            await CheckSetRights();
            DataTable booksauthors = await (new BookAuthor()).GetBooksAuthors(idBook);           
            if (booksauthors.Rows.Count == 0)
            {
                booksauthors = new DataTable();
                booksauthors.Columns.Add("idBook");
                booksauthors.Rows.Add(idBook);
            }           
            return View(booksauthors);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> GetAbsentBooksAuthors(long idBook)
        {
            ViewData["idBook"] = idBook;
            return View(await(new BookAuthor()).GetAbsentBooksAuthors(idBook));
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Create(long idBook, long idAuthor)
        {
            await (new BookAuthor()).Add(idBook, idAuthor);
            return RedirectToAction("Index", new RouteValueDictionary { { "idBook", idBook } });
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Delete(long idBook, long idAuthor)
        {
            await (new BookAuthor()).DeleteAsync(idBook, idAuthor);
            return RedirectToAction("Index", new RouteValueDictionary {{"idBook", idBook}});        
        }


        //private async Task<ActionResult> GetUserRout()
        //{
        //    ActionResult result = null;
        //    if (!(await AdminLogin.CheckLoginAdminAccess(User.Identity.Name)))
        //    {
        //        result = RedirectToAction("Index", "Book");
        //    }
        //    return result;
        //}

        private async Task CheckSetRights()
        {
            if (User.Identity.IsAuthenticated)
            {
                string login = User.Identity.Name;
                bool isAdmin = await AdminLogin.CheckLoginAdminAccess(login);
                if (isAdmin)
                {
                    ViewData["isAdmin"] = true;
                }
                else
                {
                    User us = await (new User()).GetByEmailAsync(login);
                    ViewData["idUser"] = us.IdUser;
                }
            }
        }
    }
}

BookLibrary2/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI.WebControls;
using BookLibrary2.Models;

namespace BookLibrary2.Controllers
{

    public class BookController : Controller
    {
        
        [HttpGet]
        public async Task<ActionResult> Index(int pageNumber = 1, string searchString = null)
        {          
            await CheckSetRights(); 
            DataTable table;
            do
            {
                table = await (new Book()).GetBooksByPage(pageNumber, searchString);
                if (table.Rows.Count == 0 && pageNumber > 1)
                {
                    pageNumber -= 1;
                    table = await (new Book()).GetBooksByPage(pageNumber, searchString);
                }

            } while (pageNumber > 1 && table.Rows.Count == 0);

            if (!string.IsNullOrEmpty(searchString))
            {
                ViewData["searchString"] = searchString;
            }
            else
            {
                ViewData["searchString"] = null;
            }
           
            ViewData["pageNumber"] = pageNumber;
            ViewData["pageSize"] = Book.PageSize;
            return View(table);
        }

       

        [HttpGet]
        public async Task<ActionResult> BooksByAuthor(long idAuthor, int pageNumber = 1)
        {
            await CheckSetRights();
            DataTable table;
            do
            {
                table = await (new Book()).GetBooksByAuthor(idAuthor, pageNumber);
                if (table.Rows.Count == 0 && pageNumber > 1)
                {
                    pageNumber -= 1;
                    table = await (new Book()).GetBooksByAuthor(idAuthor, pageNumber);
                }

            } while (pageNumber > 1 && table.Rows.Count == 0);
            ViewData["idAuthor"] = idAuthor;
            ViewData["pageNumber"] = pageNumber;
            ViewData["pageSize"] = Book.PageSize;
            return View(table);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
               result = View(new Book());
            }
            return result;
        }


        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(Book book)
        {
            ActionResult result;
            if (ModelState.IsValid)
            {
                await book.CreateAsync();
                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Create");
            }
            return result;
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Edit(long id)
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                Book book = await (new Book()).GetByIdAsync(id);
                if (book != null)
                {
                    result = View(book);
                }
                else
                {
                    result = RedirectToAction("Index");
                }
            }
            return result;        
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Edit(Book book)
        {
            ActionResult result;
            if (ModelState.IsValid)
            {
                await book.UpdateAsync();
                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Edit", new RouteValueDictionary { { "idBook", book.IdBook } });
            }
            return result;
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Delete(long id)
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                Book book = new Book();
                await book.DeleteAsync(id);
                result = RedirectToAction("Index");
            }
            return result;
        }



        private async Task<ActionResult> GetUserRout()
        {
            ActionResult result = null;
            if (!(await AdminLogin.CheckLoginAdminAccess(User.Identity.Name)))
            {
                result = RedirectToAction("Index", "Book");
            }
            return result;
        }

        private async Task CheckSetRights()
        {
            if (User.Identity.IsAuthenticated)
            {
                string login = User.Identity.Name;
                bool isAdmin = await AdminLogin.CheckLoginAdminAccess(login);
                if (isAdmin)
                {
                    ViewData["isAdmin"] = true;
                }
                else
                {
                    User us = await new User().GetByEmailAsync(login);
                    ViewData["idUser"] = us.IdUser;
                }
            }
        }
    }
}

BookLibrary2/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Routing.Constraints;
using BookLibrary2.Controllers;
using BookLibrary2.Models;

namespace BookLibrary2.Controllers
{
    [Authorize]
    public class HistoryController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Index(long idUser)
        {
            ViewData["isAdmin"] = await AdminLogin.CheckLoginAdminAccess(User.Identity.Name);
            return View(await (new History()).GetByUser(idUser));
        }

       [HttpGet]
        public async Task<ActionResult> BookHistory(int idBook)
        {
            return View(await (new History()).GetByBook(idBook));
        }

        //
        // GET: /History/GetAbsentBooksAuthors
        [HttpGet]
        public async Task<ActionResult> AllHistory()
        {
            return View(await (new History()).GetAll());
        }
    }
}

BookLibrary2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using BookLibrary2.Models;

namespace BookLibrary2.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                result = View(await (new User()).GetAllAsync());
            }
            return result;
        }

       
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                result = View(new User());
            }
            return result;
        }


        [HttpPost]
        public async Task<ActionResult> Create(User user)
        {
            ActionResult result = RedirectToAction("Create");
            if (ModelState.IsValid)
            {
                bool emailIsExists = await (new RegisterModel()).CheckEmail(user.Email);
                if (!emailIsExists)
                {
                    await user.CreateAsync();
                    result = RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("Email", "User with such an email already exists");
                }
               
            }            
            return result;
        }

        [HttpGet]
        public async Task<ActionResult> Edit(long idUser)
        {
            ActionResult result = await GetUserRout();
            if (result == null)
            {
                User user = await (new User()).GetByIdAsync(idUser);
                if (user != null)
                {
                    result = View(user);
                }
                else
                {
                    result = RedirectToAction("Index");
                }
            }
            return result;
        }

    
        [HttpPost]
        public async Task<ActionResult> Edit(User user)
        {
            ActionResult result = RedirectToAction("Edit", new RouteValueDictionary { { "idUser", user.IdUser } }); ;
            if (ModelState.IsValid)
            {
                bool emailIsExists = await (new RegisterModel()).CheckEmail(user.Email);
                string oldEmail = (await (new User()).GetByIdAsync(user.IdUser)).Email;
                if (!emailIsExists)
                {
                    await user.UpdateAsync();
                    result = RedirectToAction("Index");
                }
                else
                {
                    if (user.Email == oldEmail)
                    {
                        result = RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("Email", "User with such an email already exists");
                    }
                    
                }
                
            }            
            return result;          
        }

        [HttpGet]
        public async Task<ActionResult> ReceiveAbsentBooks(long idUser)
        {
            string login = User.Identity.Name;
            ViewData["isAdmin"] = await AdminLogin.CheckLoginAdminAccess(login);
            ViewData["idUser"] = idUser;
            return View(await (new User()).GetAbsentBooksAsync(idUser));
        }

        [HttpGet]
        public async Task<ActionResult> Receive(long idUser, long idBook)
        {
            await (new User()).ReceiveTheBook(idUser, idBook);
            return RedirectToAction("ReceiveAbsentBooks", new RouteValueDictionary { { "idUser", idUser } });
        }

        [HttpGet]
        public async Task<ActionResult> GetUserBooks(long idUser)
        {
            string login = User.Identity.Name;
            ViewData["isAdmin"] = await AdminLogin.CheckLoginAdminAccess(login);
            ViewData["idUser"] = idUser;
            return View(await (new User()).GetUserBooks(idUser));
        }

        [HttpGet]
        public async Task<ActionResult> Return(long idUser, long idBook)
        {
            await (new User()).Return(idUser, idBook);
            return RedirectToAction("GetUserBooks", new RouteValueDictionary { { "idUser", idUser } });
        }


        private async Task<ActionResult> GetUserRout()
        {
            ActionResult result = null;
            if (!(await AdminLogin.CheckLoginAdminAccess(User.Identity.Name)))
            {
                result = RedirectToAction("Index", "Book");
            }
            return result;
        }
    }    
}

BookLibrary2/Views/Book/BooksByAuthor.cshtml
@using System.ComponentModel.DataAnnotations
@using System.Web.UI.WebControls
@using BookLibrary2.Models
@model System.Data.DataTable
@{
    ViewBag.Title = "BooksByAuthor";
}
<!doctype html>



<html lang="en">
<head>

    <title>Book library</title>

</head>
<body>
    <h1>Author's Books</h1>
    
    @if (ViewData["isAdmin"] != null)
    {
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Book")">All books</a>
        </li>                
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "User")">Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Author")">Authors</a>
        </li>
        <li class="nav-item">
            <a class="nav-link my-lg-0" href="@Url.Action("AllHistory", "History")">History</a>
        </li>

    </ul>   
</div>
</nav>

 

    }
    else if (ViewData["idUser"] != null)           
    {
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Book")">All books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("GetUserBooks", "User", new {idUser = ViewData["idUser"]})">My books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ReceiveAbsentBooks", "User", new {idUser = ViewData["idUser"]})">Receive a book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Author")">Authors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link my-lg-0" href="@Url.Action("Index", "History", new {idUser = ViewData["idUser"]})">My history</a>
                    </li>

                </ul>         
            </div>
        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Book")">All books</a>
                    </li>                             
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Author")">Authors</a>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Login", "Account")">Enter to the site</a>
                    </li>
                </ul>
            </div>
        </nav>
    }

     
@{
    int page = (int)ViewData["pageNumber"];
    short pageSize = (short)ViewData["pageSize"];
}
<div class="table-responsive">
    <table class="table table-bordered table-striped table-condensed">
        <tr>
            <td align="center">№</td>
            <td align="center">Name</td>
            <td align="center">Publication year</td>
            <td align="center">amount</td>
        </tr>

        @for (int i = 0; i < Model.Rows.Count; i++)
        {
            <tr>
                <td>@((page - 1) * pageSize + i + 1)</td>
                <td align="left">@Model.Rows[i][1]</td>
                <td align="center">@Model.Rows[i][2]</td>
                <td align="center">@Model.Rows[i][3]</td>

                @if (ViewData["isAdmin"] != null && (bool)ViewData["isAdmin"])
                {
                    <td align="left"><a href="@Url.Action("Edit", "Book", new {id = Model.Rows[i][0]})" role="button" class="btn btn-outline-primary btn-block">Edit</a></td>
                    <td align="left"><a href="@Url.Action("Delete", "Book", new {id = Model.Rows[i][0]})" role="button" class="btn btn-outline-primary btn-block">Delete</a></td>
                    <td align="left"><a href="@Url.Action("Index", "BookAuthor", new {idBook = Model.Rows[i][0]})" role="button" class="btn btn-outline-primary btn-block">Authors</a></td>
                    <td align="left"><a href="@Url.Action("BookHistory", "History", new {idBook = Model.Rows[i][0]})" role="button" class="btn btn-outline-primary btn-block">History</a></td>
                }
                else
                {
                    <td align="left"><a href="@Url.Action("Index", "BookAuthor", new {idBook = Model.Rows[i][0]})" role="button" class="btn btn-outline-primary btn-block">Authors</a></td>
                }


            </tr>
        }
    </table>
</div>


    <nav aria-label="...">
        <ul class="pagination">

            @{
                long idAuth = 0;
                if (ViewData["idAuthor"] != null)
                {
                    idAuth = (long)ViewData["idAuthor"];
                }
            }
            @if (page == 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <li class="page-item active">
                    <a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new {idAuthor = idAuth, pageNumber = page })">@page<span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page + 1 })">@(page + 1)</a></li>
                <li class="page-item"><a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page + 2 })">@(page + 2)</a></li>
                <li class="page-item"><a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page + 2 })">@(page + 3)</a></li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page - 1 })">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page - 1 })">@(page - 1)</a></li>
                <li class="page-item active">
                    <a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page })">@page <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page + 1 })">@(page + 1)</a></li>
                <li class="page-item"><a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page + 2 })">@(page + 2)</a></li>
            }
            <li class="page-item">
                <a class="page-link" href="@Url.Action("BooksByAuthor", "Book", new { idAuthor = idAuth, pageNumber = page + 1 })">Next</a>
            </li>
        </ul>
    </nav>


<div>
    @Html.ActionLink("Main", "Index", "Book")
</div>

</body>
</html>

BookLibrary2/Views/Book/Create.cshtml
@model BookLibrary2.Models.Book

@{
    ViewBag.Title = "GetAbsentBooksAuthors";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.NameBook, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameBook)
                @Html.ValidationMessageFor(model => model.NameBook)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfPublic, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfPublic)
                @Html.ValidationMessageFor(model => model.YearOfPublic)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount)
                @Html.ValidationMessageFor(model => model.Amount)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BookLibrary2/Views/Book/Edit.cshtml
@model BookLibrary2.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(Model => Model.IdBook)
        <p></p>
        <div class="form-group">
            @Html.LabelFor(model => model.NameBook, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameBook)
                @Html.ValidationMessageFor(model => model.NameBook)
            </div>
        </div>
        <p></p>
        <div class="form-group">
            @Html.LabelFor(model => model.YearOfPublic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfPublic)
                @Html.ValidationMessageFor(model => model.YearOfPublic)
            </div>
        </div>
        <p></p>
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount)
                @Html.ValidationMessageFor(model => model.Amount)
            </div>
        </div>
        <p></p>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p></p>
<div>
    @Html.ActionLink("Back", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>